[tool.codespell]
skip = "*.gz,*.pdf"

[tool.mypy]
disallow_untyped_decorators = false
exclude = "tests/"
ignore_missing_imports = true
install_types = true
non_interactive = true

[tool.ruff]
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = [
    "I",   # isort
    "E",   # Flake8: pycodestyle (Error)
    "W",   # Flake8: pycodestyle (Warning)
    "F",   # Flake8: Pyflakes
    "B",   # Flake8: flake8-bugbear
    "C4",  # Flake8: flake8-comprehensions
    "SIM", # Flake8: flake8-simplify
    "D",   # pydocstyle
    "UP",  # pyupgrade
]
ignore = [
    "D107", # undocumented-public-init
    "D202", # blank-line-after-function. Ignore for one-line docstrings.
    "D203", # incorrect-blank-line-before-class. Conflicts with Black and D211.
    "D213", # multi-line-summary-second-line. Contradicts D212.
]

[tool.ruff.lint.isort]
classes = ["S3"]

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
